//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAgencyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AskQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AskQuestion()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public int Id { get; set; }
        public string UserEmail { get; set; }
        public string Question { get; set; }
        public int TravelerID { get; set; }
        public int AgencyID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual TripAgency TripAgency { get; set; }
        public virtual Traveler Traveler { get; set; }
    }
}
