//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAgencyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int Id { get; set; }
        public string Post1 { get; set; }
        public System.DateTime PostDate { get; set; }
        public string TripTitle { get; set; }
        public string TripDetails { get; set; }
        public string TripDestination { get; set; }
        public double TripPrice { get; set; }
        public string TripImage { get; set; }
        public int AgencyID { get; set; }
    
        public virtual TripAgency TripAgency { get; set; }
    }
}
