//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAgencyProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectDBEntities2 : DbContext
    {
        public ProjectDBEntities2()
            : base("name=ProjectDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<AskQuestion> AskQuestions { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Traveler> Travelers { get; set; }
        public virtual DbSet<TripAgency> TripAgencies { get; set; }
    }
}
